// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCxF_zBqhQTBLRlhh5KheGPez4HaHk0fHg',
    appId: '1:173372722320:web:11978bacac65614a75dc15',
    messagingSenderId: '173372722320',
    projectId: 'simi-final',
    authDomain: 'simi-final.firebaseapp.com',
    storageBucket: 'simi-final.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA7fJdyQw9B3qfG9Q2CHYgfc-Py6GNjphQ',
    appId: '1:173372722320:android:8c7690ac569a6a9d75dc15',
    messagingSenderId: '173372722320',
    projectId: 'simi-final',
    storageBucket: 'simi-final.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCn7_kklQQM9OK5m1K4YpbLOieIzu1jdiI',
    appId: '1:173372722320:ios:7f9d0a7626a6f58475dc15',
    messagingSenderId: '173372722320',
    projectId: 'simi-final',
    storageBucket: 'simi-final.appspot.com',
    iosClientId: '173372722320-jlph10kk58toadi7mlibq856061vr3ab.apps.googleusercontent.com',
    iosBundleId: 'com.example.myapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCn7_kklQQM9OK5m1K4YpbLOieIzu1jdiI',
    appId: '1:173372722320:ios:7f9d0a7626a6f58475dc15',
    messagingSenderId: '173372722320',
    projectId: 'simi-final',
    storageBucket: 'simi-final.appspot.com',
    iosClientId: '173372722320-jlph10kk58toadi7mlibq856061vr3ab.apps.googleusercontent.com',
    iosBundleId: 'com.example.myapp',
  );
}
